Repository TAMIDS-Urban-AI-Lab/CoDesign, pull requests merged in 2025-05, with the labels that each got.

#58 Prepare CoDesign to be built on EAS cloud platform
  codesign/.husky/pre-commit
  codesign/app.config.ts
  codesign/app.json
  codesign/assets/images/adaptive-icon.png
  codesign/assets/images/icon.png
  codesign/components/__tests__/report/ImageUpload-test.tsx
  codesign/eas.json
  codesign/package-lock.json
  codesign/package.json
Labels: enhancement

#103 Add Issue Template and Tweak PR Template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#89 Major ui component unit tests
  codesign/components/__tests__/ui/FloatingModal-test.tsx
  codesign/components/__tests__/ui/IconSymbol.ios.test.tsx
  codesign/components/__tests__/ui/ImageButton-test.tsx
  codesign/components/__tests__/ui/TextButton-test.tsx
  codesign/components/__tests__/ui/ThemedModal-test.tsx
  codesign/components/__tests__/ui/ThemedRadioButton-test.tsx
  codesign/components/__tests__/ui/ThemedScrollView-test.tsx
  codesign/components/__tests__/ui/ThemedTextInput-test.tsx
  codesign/components/__tests__/ui/ThemedView-test.tsx
  codesign/components/ui/FloatingModal.tsx
  codesign/components/ui/IconSymbol.ios.tsx
  codesign/components/ui/IconSymbol.tsx
  codesign/components/ui/ImageButton.tsx
  codesign/components/ui/ThemedRadioButton.tsx
Labels: Testing

#107 Add git to job environment
  .github/workflows/build-for-e2e.yml
Labels: bugfix, infra/deployment

#99 Add comments for hooks/
  codesign/hooks/__tests__/useThemeColor-test.tsx
  codesign/hooks/useColorScheme.ts
  codesign/hooks/useColorScheme.web.ts
  codesign/hooks/useFonts.ts
  codesign/hooks/useThemeColor.ts
Labels: Testing

#98 Add comments for api/
  codesign/api/__tests__/report/getImageById-test.tsx
  codesign/api/__tests__/report/getReportByBoundary-test.ts
  codesign/api/__tests__/report/uploadReport-test.tsx
  codesign/api/report/getImageById.ts
  codesign/api/report/getReportByBoundary.ts
  codesign/api/report/uploadReport.ts
Labels: Testing

#112 Update docs
  .github/ISSUE_TEMPLATE.md
  README.md
  codesign/docs/01-getting-started.md
Labels: documentation

#113 Fix Profile Page Text
  codesign/components/profile/EditProfile.tsx
  codesign/constants/styles/Typography.ts
Labels: bugfix
